openapi: 3.0.3
info:
  title: STD24215
  description: This is a reference of STD24215
  version: 1.0.0
servers:
  url: 'http://localhost:8000'
path:
  /ping:
    get:
      responses:
        '200':
          description: text brut pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
    /cars:
      get:
        summary: Récupérer la liste complète des voitures
        operationId: get_all_cars
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Car'